### ISSUE TITLE
Xcode 11正式版 run simulator 起来会崩溃

### ISSUE THREAD

**Issue by wangleiTT** [devdawei/libstdc-#6]
Traceback (most recent call last):
  File "/Applications/Reveal.app/Contents/SharedSupport/Scripts/RevealServerCommands.py", line 18, in __lldb_init_module
    HandleRevealCommand.__doc__ = CreateRevealCommandOptionsParser().format_help()
  File "/Applications/Reveal.app/Contents/SharedSupport/Scripts/RevealServerCommands.py", line 36, in CreateRevealCommandOptionsParser
    for key, info in subcommands.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
dyld: Library not loaded: /usr/lib/libstdc++.6.dylib
  Referenced from: /Users/xx/Library/Developer/CoreSimulator/Devices/CEECA0B7-6182-457A-B38F-DC6ACD5D58B9/data/Containers/Bundle/Application/097B5C06-10CF-464D-AE1D-CE3D3EB79580/xxs.app/xx
  Reason: no suitable image found.  Did find:
	/usr/lib/libstdc++.6.dylib: mach-o, but not built for iOS simulator

**Comment by devdawei** [comment]
已更新脚本
